In [1]:
import numpy as np

In [2]:
my_list1 = [1, 2, 3, 4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [5, 6, 7, 8]

In [6]:
my_array2 = np.array(my_list2)

In [7]:
my_array2

array([5, 6, 7, 8])

In [8]:
my_list = [my_list1, my_list2]

In [9]:
my_array = np.array(my_list)

In [10]:
my_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
my_array.shape


(2, 4)

In [12]:
np.zeros

<function numpy.core.multiarray.zeros>

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
zero = np.zeros(5)

In [15]:
zero.dtype

dtype('float64')

In [16]:
ones = np.ones(5, 5)

TypeError: data type not understood

In [17]:
np.ones(5, 5)

TypeError: data type not understood

In [18]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [19]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])