In [1]:
import numpy as np
from __future__ import division

In [2]:
5 / 2

2.5

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [5]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [7]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
 arr ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [10]:
arr * 3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [11]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])