In [1]:
import numpy as np
# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
# Binary Functions require two arrays
A = np.random.randn(10)

In [7]:
A

array([ 2.7240641 ,  0.55082678,  1.25872586,  0.03862855,  0.66092424,
        0.47707542, -0.27246425,  0.04221744, -0.43928187,  0.53286078])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 1.69902217, -0.13664747,  0.24078477,  0.5982544 , -0.42335101,
        2.0021776 ,  1.00728502,  0.78756582,  0.13623348, -1.23675431])

In [10]:
np.add(A, B)

array([ 4.42308627,  0.41417931,  1.49951064,  0.63688295,  0.23757323,
        2.47925302,  0.73482077,  0.82978326, -0.30304838, -0.70389353])

In [11]:
np.maximum(A, B)

array([ 2.7240641 ,  0.55082678,  1.25872586,  0.5982544 ,  0.66092424,
        2.0021776 ,  1.00728502,  0.78756582,  0.13623348,  0.53286078])

In [12]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser as wb
wb.open(website)

True